name: double-x-encoding
version: 1.2.2
synopsis: Encoding scheme to encode any Unicode string with only [0-9a-zA-Z_]
description: |
  Double-X-Encoding is an encoding scheme to encode any Unicode string
  with only characters from [0-9a-zA-Z_].
  Therefore it's quite similar to URL percent-encoding.
  It's especially useful for GraphQL ID generation,
  as it includes support for encoding leading digits and double underscores.
category: Codec, Codecs, GraphQL, ASCII, Unicode, Encoding, Decoding
github: Airsequel/double-x-encoding/Haskell
license: ISC
author: Adrian Sieber
maintainer: adrian@feram.io
extra-source-files:
  - readme.md
  - tests/blns.txt

language: GHC2021
default-extensions:
  - LambdaCase
  - MultiWayIf
  - OverloadedStrings

dependencies:
  - base >= 4.19.2 && <= 4.21
  - Cabal-syntax >= 3.10.3 && <= 3.14.2
  - text >= 2.1.1 && < 2.2

library:
  source-dirs: source
  exposed-modules: [DoubleXEncoding]

tests:
  double-x-encoding-test:
    source-dirs: tests
    main: Main.hs
    dependencies:
      - double-x-encoding
